## 模型参数已知 估计最好的Z使用

In [45]:
import numpy as np
def viterbi(trainsion_matrix, emission_matrix, pi, obs_seq):
    
    latent_nums = trainsion_matrix.shape[0]
    obs_times = len(obs_seq)
    # 矩阵中[latent_state_i, t] 表示从最开始到 t时刻的观测值 由latent_state_i 这个隐变量转换而来的最大P
    dp_matrix = np.zeros((latent_nums, obs_times))
    #dp 初始状态
    dp_matrix[:,0] = pi * emission_matrix[:,obs_seq[0]]
    
    for t in range(1, obs_times):
        #t时刻要进行n*n个计算。第一个n次是 t时刻的每个隐状态要和t-1时刻dp结果计算出最大P；第二个n是t时刻要遍历每个隐状态
        for n in range(obs_times):
            #上一时刻各个隐状态转移到n状态的概率
            t_n = dp_matrix[:, t-1] * (trainsion_matrix[:, n])
            #最大概率乘上发射到t的概率
            dp_matrix[n, t]=max(t_n) *(emission_matrix[np.argmax(t_n), obs_seq[t]])
    return dp_matrix

#隐变量
latent_variable = np.array(['Sunny', 'Cloud', 'Rainy'])
#初始状态
pi = np.array([0.3, 0.5, 0.2])
#转移矩阵
trainsion_matrix=np.array(
                  [[0.5, 0.2, 0.3],
                   [0.2, 0.1, 0.7],
                   [0.3, 0.3, 0.4]])
#发射矩阵 shape=(3, 4) 3个隐状态 4个观测状态
emission_matrix=np.array(
                 [[0.6, 0.2, 0.1, 0.1],
                  [0.4, 0.2, 0.2, 0.2],
                  [0.3, 0.1, 0.3, 0.3]])
#观测序列
obs_seq=[0,2,3]
#已知hmm的三个参数[发射矩阵,转移矩阵,初始状态]和一个观测序列，求最有可能的隐变量序列
dp_matrix = viterbi(trainsion_matrix, emission_matrix, pi, obs_seq)
print(F)
'''
[[0.18    0.009   0.00252]
 [0.2     0.0036  0.00252]
 [0.06    0.028   0.00336]]
'''
latent_path = []
for col in range(dp_matrix.shape[1]):
    latent_path.append(np.argmax(dp_matrix[:, col]))


[[0.18    0.009   0.00252]
 [0.2     0.0036  0.00252]
 [0.06    0.028   0.00336]]
